// AUTO-GENERATED by deploy session — do not edit by hand.
// Regenerated on every release; check-in only updates the fallback.
using System.Reflection;

[assembly: AssemblyVersion("2.0.2327.332")]
[assembly: AssemblyFileVersion("2.0.2327.332")]
[assembly: AssemblyInformationalVersion("2.0.23270332")]
