// AUTO-GENERATED by build-release.bat — do not edit by hand.
// Regenerated on every release; check-in only updates the fallback.
using System.Reflection;

[assembly: AssemblyVersion("2.0.2403.1432")]
[assembly: AssemblyFileVersion("2.0.2403.1432")]
[assembly: AssemblyInformationalVersion("2.0.24031432")]
