// AUTO-GENERATED by build-release.bat — do not edit by hand.
// Regenerated on every release; check-in only updates the fallback.
using System.Reflection;

[assembly: AssemblyVersion("2.2.1.0")]
[assembly: AssemblyFileVersion("2.2.1.0")]
[assembly: AssemblyInformationalVersion("2.2.1")]
